// <auto-generated />
using CareerGauge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CareerGauge.Infrastructure.Migrations
{
    [DbContext(typeof(CareerGaugeDbContext))]
    [Migration("20260903152346_InitialCareerGauge")]
    partial class InitialCareerGauge
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CareerGauge.Domain.Entities.CareerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CareerProfiles", (string)null);
                });

            modelBuilder.Entity("CareerGauge.Domain.Entities.CareerSkillRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CareerProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("CareerProfileId", "SkillId")
                        .IsUnique();

                    b.ToTable("CareerSkillRequirements", (string)null);
                });

            modelBuilder.Entity("CareerGauge.Domain.Entities.Learner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"Email\" IS NOT NULL");

                    b.ToTable("Learners", (string)null);
                });

            modelBuilder.Entity("CareerGauge.Domain.Entities.LearnerSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("integer");

                    b.Property<int>("LearnerId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("LearnerId", "SkillId")
                        .IsUnique();

                    b.ToTable("LearnerSkills", (string)null);
                });

            modelBuilder.Entity("CareerGauge.Domain.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills", (string)null);
                });

            modelBuilder.Entity("CareerGauge.Domain.Entities.CareerSkillRequirement", b =>
                {
                    b.HasOne("CareerGauge.Domain.Entities.CareerProfile", "CareerProfile")
                        .WithMany("SkillRequirements")
                        .HasForeignKey("CareerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareerGauge.Domain.Entities.Skill", "Skill")
                        .WithMany("CareerSkillRequirements")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareerProfile");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("CareerGauge.Domain.Entities.LearnerSkill", b =>
                {
                    b.HasOne("CareerGauge.Domain.Entities.Learner", "Learner")
                        .WithMany("LearnerSkills")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareerGauge.Domain.Entities.Skill", "Skill")
                        .WithMany("LearnerSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Learner");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("CareerGauge.Domain.Entities.CareerProfile", b =>
                {
                    b.Navigation("SkillRequirements");
                });

            modelBuilder.Entity("CareerGauge.Domain.Entities.Learner", b =>
                {
                    b.Navigation("LearnerSkills");
                });

            modelBuilder.Entity("CareerGauge.Domain.Entities.Skill", b =>
                {
                    b.Navigation("CareerSkillRequirements");

                    b.Navigation("LearnerSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
